services:
  postgresdb-api:
    image: postgres:latest
    container_name: api-postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./datos-postgres:/var/lib/postgresql/data

volumes:
  datos-postgres: