services:
  postgresdb-api:
    image: postgres:18-alpine
    container_name: api-postgres-db
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak
    command: start-dev
    ports:
      - "8180:8080"
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
  todo-app-native:
    image: todo-app:0.0.2-SNAPSHOT
    container_name: todo-app-native
    env_file:
      - .env
    depends_on:
      postgresdb-api:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  postgres_data: