services:
  postgresdb-api:
    image: postgres:18-alpine
    container_name: api-postgres-db
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  todo-app-native:
    image: todo-app:0.2.1-SNAPSHOT
    container_name: todo-app-native
    env_file:
      - .env
    depends_on:
      postgresdb-api:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  postgres_data: